---
title: "Introduction to R<br> <span style='color: gray'>Summary"
author: "Marzena Marszałek<br> marzena.marszalek@doctoral.uj.edu.pl<br>"
date: "`r Sys.Date()`"
chunk_output_type: console
output:
  github_document:
      toc: true
---

## Class 1
  
  - `+`  - addition
  - `-`  - subtraction
  - `*`  - multiplication
  - `/`  - division
  - `^`  - exponentiation
  - `%%`  - modulo
  - `%/%`  - integer division
  - `log()`   - natural logarithm
  - `log10()`   - logarithm base 10
  - `exp()`   - exponent
  - `sin()`, `cos()`, `tan()`  - trigonometric functions    
  - `abs()`  - absolute value
  - `paste()`   - converts its arguments to character strings
  - `seq()`   - generates a sequence of numbers
  - `rep()`   -  repeats a vector x in various ways
  - `min()` - minimum value
  - `max()`   - maximum value
  - `sum()`   - sum up all numbers in a vector
  - `prod()`    - multiply all numbers in a vector
  - `mean()`    - average value
  - `median()`    - central value
  - `length()`    - number of elements in a vector
  - `sort()`    - sort values (default is ascending order, use decreasing argument to sort in descending order)
  - `unique()`    - return unique values
  - `round()`   - round numbers (to integers by default)

## Class 2

  - `install.packages()` - installs indicated package
  - `library()` - loads indicated package
  - `getwd()`  - prints current working directory
  - `setwd()`  - sets working directory for current session
  - `class()`  - prints the names of classes of an object
  - `read_excel()`  - reads an excel (.xls and .xlsx) files 
  - `read.csv()`  - reads .csv files  
  - `read.table()`  - reads a file in table format and creates a data frame from it  
  - `write.table()`  - prints an object to a file
  - `write_xlsx()`  - writes a data frame to an .xlsx file


## Class 3

  - `head()`    - prints the first n lines of an object  
  - `tail()`    -  prints the last n lines of an object  
  - `summary()`   - summarizes the values in a vector or data frame  
  - `str()` - shows the structure of an object  
  - `ncol()`  - prints the number of column  of an object
  - `nrow()` - prints the number of rows of an object
  - `dim()` - prints the dimensions of on object (number of rows and columns)
  - `as.character()` - converts a numeric object to a string data type or a character object
  - `as.factor()` - converts a column from numeric to factor
  - `as.numeric()` - converts a character vector into a numeric vector
  - `na.omit()` - removes any observation with missing values (NA) from a vector, matrix, or data frame
  - `cbind()` - combines R objects by columns
  - `rbind()` combines R objects by columns
  - `data.frame()` -  creates data frames

## Class 4

  - Logical operators:
    -  `==`   - equal
    - `!=`    - unequal
    - `>`   - greater than
    - `>=`    - greater than or equal
    - `<`   - less than
    - `<=`    - less than or equal
  - `is.na()` - checks for missing values in vectors and data frames
  - `sum()` - returns the sum of all its arguments
  - `mean()` - returns arithmetic mean 
  - `identical()` - checks whether two objects in R are exactly equal, function returns the logical vector
  - `%in%` - checks if the value in the first argument is present in the second argument, function returns the logical vector
  - `which()` - returns vector of the positions of the values that satisfies given conditions 
  - `arrange()` - orders the rows according to the values of selected columns
  - `select()` - selects specific columns within your data 
  - `filter()` -  subsets a data frame, retaining all rows that satisfy given conditions
  - `mutate()` - creates new columns that are functions of existing variables
  - `summarise()` - summarises grouped data (grouped with group_by() function)
  - `count()` - count the observations in each group, it is a simplified combination of group_by() and summarise()
  - `group_by()` - groups the data according to given columns
  - `left_join()` - joins 2 data frames based on a common column, preserving all rows from the first data frame
  - `right_join()` - joins 2 data frames based on a common column, preserving all rows from the second data frame
  - `inner_join()` - joins 2 data frames based on a common column, preserving only rows that are common to both data frames
  - `full_join` - - joins 2 data frames based on a common column, preserving all rows from both data frames and replacing missing values with `NA`
  
## Class 5

  - `plot()` - base R function, creates various types of plots
  - `hist()` - base R function, creates histograms
  - `ggplot()` - `ggplot2` package function, used to create plots, constructs the initial plot object,
  - `ggsave()` -  export `ggplot2` plots to image files or vector graphics. 
  - `png()`  -  opens a PNG device for saving plots as PNG files
  - `dev.off()` -  closes a PNG device for saving plots as PNG files